version: '3.8'

services:
  # 1. Servicio de Base de Datos PostgreSQL
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ticket_user       # USUARIO DE LA BD
      POSTGRES_PASSWORD: ticket_pass   # CONTRASEÑA DE LA BD
      POSTGRES_DB: senai_db            # NOMBRE DE LA BD
    ports:
      - "5433:5432" # Mapea el puerto del contenedor al puerto local
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistencia de datos

  # 2. Servicio de tu Servidor Node.js (opcional por ahora, lo haremos después)
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

volumes:
  postgres_data: